### ISSUE TITLE
conda `r-rsqlite` and R SQLite

### ISSUE THREAD

**Issue by Shicheng-Guo** [r-dbi/RSQLite#377] opened 2021-07-25 19:40 UTC
Any suggestion to install SQLite with conda? It looks only 2.2.5 version is found in conda rather than 2.2.7

https://anaconda.org/conda-forge/r-rsqlite

Thanks

**Comment by krlmlr** [comment] 2021-08-21 02:03
Thanks. Is this a duplicate of #367?

**Closed** 2021-08-21 07:22 UTC
