### ISSUE TITLE
request: update to new SQLite version

### ISSUE THREAD

**Issue by alanpaulkwan** [r-dbi/RSQLite#270] opened 2018-10-24 01:51 UTC
SQLite 3.25 supports window functions - may I please kindly request this as a feature? It would be a huge boon. Thanks.

**Comment by hermandr** [comment] 2018-10-29 04:30
+1 on this request please!

**Comment by colearendt** [comment] 2018-11-08 03:34
Duplicate of #268

**Closed** 2018-11-26 11:10 UTC

**Comment by krlmlr** [comment] 2018-11-26 11:13
Closed as duplicate.
